import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class MainParser {
	//list of all the elements
	private String location;
	private String weather;
		private double temp;
		private double temphigh;
		private double templow;
		
		
		public void weatherAPI(String input) throws Exception 
		{
			String Location;
				
			//key generated by the open weather 
			final String key ="70974c8a07e37252d786fb310a6c05f9";
			
			
			String endpoint = "http://api.openweathermap.org/data/2.5/forecast?id=524901&APPID=";
			
			String myAPIurl = "http://api.openweathermap.org/data/weather?q=";

			
		            //this makes a GET request to the API
		            URL url = new URL("http://api.openweathermap.org/data/2.5/weather?q=" + input + "&APPID=70974c8a07e37252d786fb310a6c05f9");
		            HttpURLConnection http = (HttpURLConnection) url.openConnection();
		         
		            http.setRequestMethod("GET");

		            //reading in data from the APU
		            BufferedReader reader = new BufferedReader(new InputStreamReader(http.getInputStream()));
		            StringBuilder result = new StringBuilder();

		            String line;
		            while ((line = reader.readLine()) != null) {
		                result.append(line);
		            }
		            
		            String newResult;
		            newResult= result.toString();
		            
		       
		            reader.close();
		            
		            //returning the data
		            parsingJSON(newResult);
		            
		   
		 
		    }
		
		 public void  parsingJSON(String newResult) {
		        
			 // Parse  JSON string 
		        JsonObject obj = new JsonParser().parse(newResult).getAsJsonObject();

		        // Get the data from "main"
		        JsonObject obj_main = obj.getAsJsonObject("main");

		        // Get the temperatures 
		        double tempF = obj_main.get("temp").getAsDouble()-273.15;
		        double highF = obj_main.get("temp_max").getAsDouble()-273.15;
		        double lowF = obj_main.get("temp_min").getAsDouble()-273.15;
		    

		        // Get weather from the main object of first element of "weather" array in the "main" object.
		        String weather = obj.getAsJsonArray("weather").get(0).getAsJsonObject().get("description").getAsString();

		        // Get the location name 
		        String location = obj.get("name").getAsString();

		        // Return fetched data as a WeatherData object.
		        MainParsing(tempF, highF, lowF, location, weather);
		}

		
		public void MainParsing(double temp, double temphigh, double templow, String location, String weather) {
			this.temp = temp;
			this.temphigh = temphigh;
			this.templow = templow;
			this.location = location;
			this.weather = weather;
		}
		
		
		
		public String toString() {
	        return String.format("The weather in %s is %s. The temperature is %.1f°C, with a high of %.1f°C and a low of %.1f°C.", location, weather, temp, temphigh, templow);
		}
		
		
		//create getter and setter functions for all of these
		
		public void set_high(double high) {
			this.temphigh = (1.8 * (high - 273) + 32);
		}
		
		public double get_high() {
			return (1.8 * (temphigh - 273) + 32);
		}
		
		public void set_low(double low) {
			this.templow = (1.8 * (low - 273) + 32);;
		}
		
		public double get_low() {
			return (1.8 * (templow - 273) + 32);
		}
		
		public void set_temp(double temp) {
			this.temp = (1.8 * (temp - 273) + 32);;
		}
		
		public void set_weather(String weather) {
			this.weather = weather;
		}
		
		public String get_weather() {
			return weather;
		}
		
		public void set_location(String location) {
			this.location = location;
		}
		
		public String get_location() {
			return location;
		}
	}

	
	
	

